
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <title>Mock</title>
    <style type="text/css">
        html{font-size: 62.5%;}
        body{margin: 0; padding:0;}
        article{display: block;}
        body{font-size: 1.4rem;color: #333;}
        .content{padding:4px 1em 1em;font-size: 1.4rem;word-wrap: break-word;}
        .content h3 {font-size: 1.8rem;margin:0 0 1em;}
        .content p{line-height: 1.8em;margin-bottom: 1em;}
        .content .item{line-height:0.8em;}
    </style>
</head>
<body>
<div>
    <article class="content">
        <h3>Hello World</h3>
    </article>
</div>
</body>
</html>
